---
- name: Setup kubectl access on bastion node
  hosts: bastion
  become: true
  gather_facts: true
  vars:
    target_group: "{{ target | default('rancher') }}"
  tasks:
    - name: Extract Kubernetes version from RKE2 version
      ansible.builtin.set_fact:
        k8s_version: "{{ rke2_version | regex_replace('^v([0-9]+\\.[0-9]+\\.[0-9]+).*', 'v\\1') }}"

    - name: Display Kubernetes version for kubectl
      ansible.builtin.debug:
        msg: "Installing kubectl version {{ k8s_version }} to match RKE2 {{ rke2_version }}"

    - name: Download kubectl binary matching RKE2 Kubernetes version
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ k8s_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
        owner: root
        group: root
      register: kubectl_download
      retries: 3
      delay: 5

    - name: Verify kubectl installation
      ansible.builtin.command: kubectl version --client
      register: kubectl_version_output
      changed_when: false

    - name: Display kubectl version
      ansible.builtin.debug:
        msg: "kubectl installed: {{ kubectl_version_output.stdout }}"

    - name: Create .kube directory for root
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Create .kube directory for ansible user
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      when: ansible_user is defined and ansible_user != 'root'

    - name: Fetch KUBECONFIG from first airgap node
      ansible.builtin.fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: /tmp/rke2-{{ inventory_hostname }}.yaml
        flat: true
      delegate_to: "{{ groups[target_group][0] }}"
      become: true

    - name: Read kubeconfig content
      ansible.builtin.slurp:
        src: "/tmp/rke2-{{ inventory_hostname }}.yaml"
      register: kubeconfig_content
      delegate_to: localhost
      become: false

    - name: Update server URL in kubeconfig content
      ansible.builtin.set_fact:
        updated_kubeconfig: >-
          {{ (kubeconfig_content.content | b64decode) |
          regex_replace('https://127\.0\.0\.1:6443',
          'https://' + hostvars[groups[target_group][0]]['ansible_host'] + ':6443') }}

    - name: Write kubeconfig to bastion root
      ansible.builtin.copy:
        content: "{{ updated_kubeconfig }}"
        dest: /root/.kube/config
        mode: '0600'
        owner: root
        group: root

    - name: Write kubeconfig to ansible user
      ansible.builtin.copy:
        content: "{{ updated_kubeconfig }}"
        dest: "/home/{{ ansible_user }}/.kube/config"
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      when: ansible_user is defined and ansible_user != 'root'

    - name: Clean up temporary kubeconfig
      ansible.builtin.file:
        path: "/tmp/rke2-{{ inventory_hostname }}.yaml"
        state: absent
      delegate_to: localhost
      become: false

    - name: Test kubectl connectivity
      ansible.builtin.shell: kubectl get nodes -o wide
      # Using shell because we need to set environment variables
      environment:
        KUBECONFIG: /root/.kube/config
      register: kubectl_test
      failed_when: false
      changed_when: false

    - name: Display kubectl test results
      ansible.builtin.debug:
        msg: |
          kubectl connectivity test:
          {% if kubectl_test.rc == 0 %}
          SUCCESS - Cluster accessible from bastion:
          {{ kubectl_test.stdout }}
          {% else %}
          FAILED - Error connecting to cluster:
          {{ kubectl_test.stderr }}

          Troubleshooting steps:
          1. Verify RKE2 is running on airgap nodes
          2. Check network connectivity from bastion to airgap nodes
          3. Verify kubeconfig server URL is correct
          {% endif %}

    - name: Display final instructions
      ansible.builtin.debug:
        msg: |
          kubectl Access Setup Complete!

          [OK] kubectl installed on bastion node
          [OK] KUBECONFIG copied and configured

          To manage your cluster from the bastion node:

          As root:
          kubectl get nodes
          kubectl get pods -A
          kubectl get services -A

          As {{ ansible_user | default('your user') }}:
          kubectl get nodes
          kubectl get pods -A
          kubectl get services -A

          The kubeconfig is located at:
          - /root/.kube/config
          {% if ansible_user is defined and ansible_user != 'root' %}
          - /home/{{ ansible_user }}/.kube/config
          {% endif %}

          You can also use kubectl with explicit kubeconfig:
          kubectl --kubeconfig=/root/.kube/config get nodes
