---
# This role now delegates to rke2_bundle_manager for improved modularity
# The rke2_bundle_manager role handles downloading, verification, and bundle creation

- name: Use rke2_bundle_manager to create RKE2 bundle
  ansible.builtin.include_role:
    name: rke2_bundle_manager

- name: Display bundle contents for verification
  ansible.builtin.command: tar tvf {{ rke2_bundle_dir | default('/opt/rke2-files') }}/{{ rke2_bundle_filename | default('rke2-bundle.tar.gz') }}
  register: bundle_contents
  changed_when: false
  become: true

- name: Show bundle structure
  ansible.builtin.debug:
    msg: "Bundle contents:\n{{ bundle_contents.stdout_lines | join('\n') }}"
    verbosity: 1
