---
# Create RKE2 bundle tarball from downloaded artifacts

- name: Create bundle destination directory
  ansible.builtin.file:
    path: "{{ rke2_bundle_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Create staging directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - "{{ rke2_staging_dir }}/tmp"
    - "{{ rke2_staging_dir }}/tmp/rke2-artifacts"
  become: true

- name: Copy files to staging directory
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: preserve
    remote_src: true
  loop:
    - src: /tmp/rke2-install.sh
      dest: "{{ rke2_staging_dir }}/tmp/rke2-install.sh"
    - src: "{{ rke2_temp_dir }}/rke2.linux-{{ rke2_arch }}.tar.gz"
      dest: "{{ rke2_staging_dir }}/tmp/rke2-artifacts/rke2.linux-{{ rke2_arch }}.tar.gz"
    - src: "{{ rke2_temp_dir }}/rke2-images.tar.gz"
      dest: "{{ rke2_staging_dir }}/tmp/rke2-artifacts/rke2-images.tar.gz"
    - src: "{{ rke2_temp_dir }}/sha256sum-{{ rke2_arch }}.txt"
      dest: "{{ rke2_staging_dir }}/tmp/rke2-artifacts/sha256sum-{{ rke2_arch }}.txt"
  become: true

- name: Create archive of RKE2 files
  community.general.archive:
    path: "{{ rke2_staging_dir }}/tmp"
    dest: "{{ rke2_bundle_dir }}/{{ rke2_bundle_filename }}"
    format: gz
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    remove: true
  become: true
  register: bundle_created

- name: Verify bundle creation
  ansible.builtin.stat:
    path: "{{ rke2_bundle_dir }}/{{ rke2_bundle_filename }}"
  register: bundle_check
  failed_when: not bundle_check.stat.exists

- name: Display bundle information
  ansible.builtin.debug:
    msg: |
      RKE2 Bundle Created Successfully:
      - Location: {{ rke2_bundle_dir }}/{{ rke2_bundle_filename }}
      - Size: {{ (bundle_check.stat.size / 1024 / 1024) | round(2) }} MB
      - Version: {{ rke2_version }}

- name: Clean up temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ rke2_staging_dir }}"
    - "{{ rke2_temp_dir }}"
    - /tmp/rke2-install.sh
  become: true
  when: rke2_cleanup_temp_files | bool
