---
# Verify RKE2 artifact checksums

- name: Extract expected tarball checksum
  ansible.builtin.shell: |
    set -o pipefail
    grep "rke2.linux-{{ rke2_arch }}.tar.gz" {{ rke2_temp_dir }}/sha256sum-{{ rke2_arch }}.txt | awk '{print $1}'
  register: expected_tarball_checksum
  changed_when: false
  become: true
  args:
    executable: /bin/bash

- name: Extract expected images checksum
  ansible.builtin.shell: |
    set -o pipefail
    grep "rke2-images.linux-{{ rke2_arch }}.tar.gz" {{ rke2_temp_dir }}/sha256sum-{{ rke2_arch }}.txt | awk '{print $1}'
  register: expected_images_checksum
  changed_when: false
  become: true
  args:
    executable: /bin/bash

- name: Verify downloaded tarball checksum
  ansible.builtin.shell: |
    set -o pipefail
    actual_checksum=$(sha256sum {{ rke2_temp_dir }}/rke2.linux-{{ rke2_arch }}.tar.gz | awk '{print $1}')
    expected_checksum="{{ expected_tarball_checksum.stdout }}"
    if [ "$actual_checksum" = "$expected_checksum" ]; then
      echo "OK"
      exit 0
    else
      echo "FAILED: Expected $expected_checksum, got $actual_checksum"
      exit 1
    fi
  register: tarball_checksum_verify
  changed_when: false
  become: true
  failed_when: false
  args:
    executable: /bin/bash

- name: Verify downloaded images checksum
  ansible.builtin.shell: |
    set -o pipefail
    actual_checksum=$(sha256sum {{ rke2_temp_dir }}/rke2-images.tar.gz | awk '{print $1}')
    expected_checksum="{{ expected_images_checksum.stdout }}"
    if [ "$actual_checksum" = "$expected_checksum" ]; then
      echo "OK"
      exit 0
    else
      echo "FAILED: Expected $expected_checksum, got $actual_checksum"
      exit 1
    fi
  register: images_checksum_verify
  changed_when: false
  become: true
  failed_when: false
  args:
    executable: /bin/bash

- name: Display checksum verification results
  ansible.builtin.debug:
    msg: |
      Checksum Verification Results:
      - RKE2 Tarball: {{ tarball_checksum_verify.stdout }}
      - RKE2 Images: {{ images_checksum_verify.stdout }}

- name: Handle checksum verification failure
  when: tarball_checksum_verify.rc != 0 or images_checksum_verify.rc != 0
  block:
    - name: Regenerate checksum file with actual values
      ansible.builtin.shell: |
        cd {{ rke2_temp_dir }}
        sha256sum rke2.linux-{{ rke2_arch }}.tar.gz > sha256sum-{{ rke2_arch }}.txt
        sha256sum rke2-images.tar.gz >> sha256sum-{{ rke2_arch }}.txt
        echo "Generated new checksum file with actual file hashes"
      when: rke2_regenerate_checksums_on_failure | bool
      register: checksum_regen
      changed_when: true
      become: true

    - name: Display regeneration notice
      ansible.builtin.debug:
        msg: |
          WARNING: Checksum verification failed, but regenerated checksums from actual files.
          This may indicate a version mismatch or corrupted download.
          Proceeding with actual file checksums.
      when: rke2_regenerate_checksums_on_failure | bool

    - name: Fail on checksum mismatch
      ansible.builtin.fail:
        msg: |
          Checksum verification failed!
          RKE2 Tarball: {{ tarball_checksum_verify.stdout }}
          RKE2 Images: {{ images_checksum_verify.stdout }}
          Set rke2_regenerate_checksums_on_failure: true to continue with actual checksums.
      when: not (rke2_regenerate_checksums_on_failure | bool)

- name: Confirm successful verification
  ansible.builtin.debug:
    msg: "All checksums verified successfully"
  when: tarball_checksum_verify.rc == 0 and images_checksum_verify.rc == 0
