---
- name: Fix RKE2 Configuration and Restart Service
  hosts: airgap_nodes
  become: true
  gather_facts: true
  vars:
    target_group: "{{ target | default('rancher') }}"
  tasks:
    - name: Stop RKE2 server service
      ansible.builtin.systemd:
        name: rke2-server
        state: stopped
      failed_when: false

    - name: Remove old RKE2 configuration
      ansible.builtin.file:
        path: /etc/rancher/rke2/config.yaml
        state: absent

    - name: Regenerate RKE2 server configuration
      ansible.builtin.template:
        src: roles/rke2_install/templates/config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname == groups[target_group][0]

    - name: Regenerate RKE2 agent configuration for additional nodes
      ansible.builtin.template:
        src: roles/rke2_install/templates/agent-config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname != groups[target_group][0]

    - name: Display new RKE2 configuration
      ansible.builtin.command: cat /etc/rancher/rke2/config.yaml
      register: new_config
      changed_when: false

    - name: Show new configuration
      ansible.builtin.debug:
        msg: |
          New RKE2 Configuration:
          {{ new_config.stdout }}

    - name: Start RKE2 server service
      ansible.builtin.systemd:
        name: rke2-server
        state: started
        enabled: true
      when: inventory_hostname == groups[target_group][0]

    - name: Wait for RKE2 server to be ready
      ansible.builtin.wait_for:
        path: /var/lib/rancher/rke2/server/token
        timeout: 300
      when: inventory_hostname == groups[target_group][0]

    - name: Get server token for agent nodes
      ansible.builtin.slurp:
        src: /var/lib/rancher/rke2/server/token
      register: server_token
      when: inventory_hostname == groups[target_group][0]

    - name: Set server token fact
      ansible.builtin.set_fact:
        rke2_token: "{{ hostvars[groups[target_group][0]]['server_token']['content'] | b64decode | trim }}"
      when: inventory_hostname != groups[target_group][0]

    - name: Update agent configuration with server token
      ansible.builtin.template:
        src: roles/rke2_install/templates/agent-config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname != groups[target_group][0]

    - name: Start RKE2 agent service on additional nodes
      ansible.builtin.systemd:
        name: rke2-agent
        state: started
        enabled: true
      when: inventory_hostname != groups[target_group][0]

    - name: Check RKE2 service status
      ansible.builtin.systemd:
        name: "{{ 'rke2-server' if inventory_hostname == groups[target_group][0] else 'rke2-agent' }}"
      register: rke2_status

    - name: Display RKE2 service status
      ansible.builtin.debug:
        msg: |
          RKE2 Service Status:
          Name: {{ rke2_status.name }}
          State: {{ rke2_status.status.ActiveState }}
          Enabled: {{ rke2_status.status.UnitFileState }}
