# renovate: datasource=docker depName=cypress/factory
FROM cypress/factory:7.3.1@sha256:beb1107f12f2b9a0950d15ee5188f4fe9f049c620960ce3440accacbbc659afa

# renovate: datasource=github-release-attachments depName=kubernetes/kubernetes
ENV KUBECTL_VERSION=v1.33.10
# renovate: datasource=github-release-attachments depName=kubernetes/kubernetes digestVersion=v1.33.10
ENV KUBECTL_SUM=f156acb753ee4366789ab7a663916eb580e7ee1b9e449bc9b052181db524e3f5

RUN wget -q "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -O /tmp/kubectl && \
    echo "${KUBECTL_SUM}  /tmp/kubectl" | sha256sum -c - && \
    mv /tmp/kubectl /bin/kubectl && \
    chmod +x /bin/kubectl
RUN mkdir -p /root/.kube

COPY imported_config /root/.kube/config

ENTRYPOINT ["bash", "cypress/jenkins/cypress.sh"]